### ISSUE TITLE
gson returns invalid json

### ISSUE THREAD

**Issue by 3nuc** [3nuc/tworzenie-aplikacji-sieciowych#2]
hi Tomasz theres a problem with the newest Glock 21 model you've provided

you see if you upload the 
https://raw.githubusercontent.com/3nuc/tworzenie-aplikacji-sieciowych/master/datasets/irysy.csv

file, the string values are like `versicolor` not `"versicolor"`

if you later use the very same file for eg /getNearestNeighbors, the returned neighbors will be like `[[0.1,0.2,versicolor]]`, which is invalid JSON (should be `[[0.1,0.2,"versicolor]]`

tbh I'm wondering why is the library even allowed to return invalid json, shouldn't the lib behave like "ah you're passing versicolor, so you probably want to send it as a valid JSON string, not as literally `versicolor` which no browser will be able to parse"

**Comment by 3nuc** [comment]
or eg 
![image](https://user-images.githubusercontent.com/5359825/119260752-842dff80-bbd4-11eb-9a75-91221ad13e5b.png)
![image](https://user-images.githubusercontent.com/5359825/119260764-8abc7700-bbd4-11eb-918d-0dcc0145553c.png)

**Comment by tonio965** [comment]
Dear 3nuc, absolutely horrendous that this lib even allows that... Will check it and hopefully fix in the following release. Need to whoop those Gson's bastards asses rn

**Comment by 3nuc** [comment]
большое спасибо Tomasz

**Comment by tonio965** [comment]
Dear @3nuc I changed creation of JSON there, please take a look and let me know if that has fixed your issue.
Best regards, TK
